//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sorter.localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resources_uk {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resources_uk() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sorter.localization.resources.uk", typeof(resources_uk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to А-Я.
        /// </summary>
        internal static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Двійкові числа.
        /// </summary>
        internal static string BinaryNumRatioBut {
            get {
                return ResourceManager.GetString("BinaryNumRatioBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортування бульбашкою.
        /// </summary>
        internal static string BubbleRadioBut {
            get {
                return ResourceManager.GetString("BubbleRadioBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to очистити.
        /// </summary>
        internal static string ClearButton {
            get {
                return ResourceManager.GetString("ClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортування перемішуванням.
        /// </summary>
        internal static string CocktailRadioBut {
            get {
                return ResourceManager.GetString("CocktailRadioBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to скопіювати.
        /// </summary>
        internal static string CopyButton {
            get {
                return ResourceManager.GetString("CopyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скопійовано до буферу обміну.
        /// </summary>
        internal static string CopyClipboardMessage {
            get {
                return ResourceManager.GetString("CopyClipboardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Десяткові числа.
        /// </summary>
        internal static string DecimalNumRationBut {
            get {
                return ResourceManager.GetString("DecimalNumRationBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я-А.
        /// </summary>
        internal static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Англійский алфавіт.
        /// </summary>
        internal static string EnglishLettersRationBut {
            get {
                return ResourceManager.GetString("EnglishLettersRationBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл збережений.
        /// </summary>
        internal static string FileSaveText {
            get {
                return ResourceManager.GetString("FileSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шістнадцяткові числа.
        /// </summary>
        internal static string HexadecimalNumRatioBut {
            get {
                return ResourceManager.GetString("HexadecimalNumRatioBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ігнорувати Дублікати.
        /// </summary>
        internal static string IgnoreDuplicateCheckBox {
            get {
                return ResourceManager.GetString("IgnoreDuplicateCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введення.
        /// </summary>
        internal static string InputLabel {
            get {
                return ResourceManager.GetString("InputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вхідний роздільник.
        /// </summary>
        internal static string InputSeparatorLabel {
            get {
                return ResourceManager.GetString("InputSeparatorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортування вставками.
        /// </summary>
        internal static string InsertionRadioBut {
            get {
                return ResourceManager.GetString("InsertionRadioBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to довж.
        /// </summary>
        internal static string LengthNumLabel {
            get {
                return ResourceManager.GetString("LengthNumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розмір слів.
        /// </summary>
        internal static string LengthWordRatioBut {
            get {
                return ResourceManager.GetString("LengthWordRatioBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортування злиттям.
        /// </summary>
        internal static string MergeRadioBut {
            get {
                return ResourceManager.GetString("MergeRadioBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to відкрити.
        /// </summary>
        internal static string OpenButton {
            get {
                return ResourceManager.GetString("OpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виведення.
        /// </summary>
        internal static string OutputLabel {
            get {
                return ResourceManager.GetString("OutputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вихідний роздільник.
        /// </summary>
        internal static string OutputSeparatorLabel {
            get {
                return ResourceManager.GetString("OutputSeparatorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to перест.
        /// </summary>
        internal static string PermutationLabel {
            get {
                return ResourceManager.GetString("PermutationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зразок.
        /// </summary>
        internal static string SampleLabel {
            get {
                return ResourceManager.GetString("SampleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to зберегети.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортування вибіркою.
        /// </summary>
        internal static string SelectionRadioBut {
            get {
                return ResourceManager.GetString("SelectionRadioBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування.
        /// </summary>
        internal static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортувати.
        /// </summary>
        internal static string SortButton {
            get {
                return ResourceManager.GetString("SortButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to час.
        /// </summary>
        internal static string TimeLabel {
            get {
                return ResourceManager.GetString("TimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортувальник.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Українский алфавіт.
        /// </summary>
        internal static string UkrainianLettersRationBut {
            get {
                return ResourceManager.GetString("UkrainianLettersRationBut", resourceCulture);
            }
        }
    }
}
