//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sorter.localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sorter.localization.resources", typeof(resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary numbers.
        /// </summary>
        public static string BinaryNumRatioBut {
            get {
                return ResourceManager.GetString("BinaryNumRatioBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bubble Sort.
        /// </summary>
        public static string BubbleRadioBut {
            get {
                return ResourceManager.GetString("BubbleRadioBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear.
        /// </summary>
        public static string ClearButton {
            get {
                return ResourceManager.GetString("ClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cocktail Sort.
        /// </summary>
        public static string CocktailRadioBut {
            get {
                return ResourceManager.GetString("CocktailRadioBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy.
        /// </summary>
        public static string CopyButton {
            get {
                return ResourceManager.GetString("CopyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal numbers.
        /// </summary>
        public static string DecimalNumRationBut {
            get {
                return ResourceManager.GetString("DecimalNumRationBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English alphabet.
        /// </summary>
        public static string EnglishLettersRationBut {
            get {
                return ResourceManager.GetString("EnglishLettersRationBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexadecimal numbers.
        /// </summary>
        public static string HexadecimalNumRatioBut {
            get {
                return ResourceManager.GetString("HexadecimalNumRatioBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Duplicate.
        /// </summary>
        public static string IgnoreDuplicateCheckBox {
            get {
                return ResourceManager.GetString("IgnoreDuplicateCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string InputLabel {
            get {
                return ResourceManager.GetString("InputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Separator.
        /// </summary>
        public static string InputSeparatorLabel {
            get {
                return ResourceManager.GetString("InputSeparatorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertion Sort.
        /// </summary>
        public static string InsertionRadioBut {
            get {
                return ResourceManager.GetString("InsertionRadioBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to length.
        /// </summary>
        public static string LengthNumLabel {
            get {
                return ResourceManager.GetString("LengthNumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word size.
        /// </summary>
        public static string LengthWordRatioBut {
            get {
                return ResourceManager.GetString("LengthWordRatioBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MergeSort.
        /// </summary>
        public static string MergeRadioBut {
            get {
                return ResourceManager.GetString("MergeRadioBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open.
        /// </summary>
        public static string OpenButton {
            get {
                return ResourceManager.GetString("OpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string OutputLabel {
            get {
                return ResourceManager.GetString("OutputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Separator.
        /// </summary>
        public static string OutputSeparatorLabel {
            get {
                return ResourceManager.GetString("OutputSeparatorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to permutation.
        /// </summary>
        public static string PermutationLabel {
            get {
                return ResourceManager.GetString("PermutationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        public static string SampleLabel {
            get {
                return ResourceManager.GetString("SampleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Sort.
        /// </summary>
        public static string SelectionRadioBut {
            get {
                return ResourceManager.GetString("SelectionRadioBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string SortButton {
            get {
                return ResourceManager.GetString("SortButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        public static string TimeLabel {
            get {
                return ResourceManager.GetString("TimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorter.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian alphabet.
        /// </summary>
        public static string UkrainianLettersRationBut {
            get {
                return ResourceManager.GetString("UkrainianLettersRationBut", resourceCulture);
            }
        }
    }
}
